spring:
  datasource:
    url: jdbc:postgresql://localhost:6969/debilus_event_manager
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
