spring:
  datasource:
    url: jdbc:postgresql://localhost:6969/debilus_event_manager
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd
